# Generated by Django 2.2.1 on 2019-07-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alter_execute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('AlterID', models.CharField(max_length=50)),
                ('Hospital', models.CharField(max_length=25)),
                ('Executor', models.CharField(max_length=50)),
                ('ExecutionTime', models.DateTimeField(auto_now=True)),
                ('ExecutionResult', models.TextField(max_length=500)),
            ],
            options={
                'db_table': 'alt_execute',
            },
        ),
    ]
