# Generated by Django 2.2.1 on 2019-09-06 15:29

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alter_execute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('alterid', models.CharField(max_length=50)),
                ('hospitalid', models.CharField(max_length=5)),
                ('databaseid', models.IntegerField(max_length=11)),
                ('executor', models.CharField(max_length=50)),
                ('executiontime', models.DateTimeField(auto_now=True)),
                ('executionresult', models.CharField(max_length=500)),
                ('exportlist', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'db_table': 'alt_execute',
            },
        ),
    ]
