# Generated by Django 2.2.1 on 2019-08-21 06:59

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Alter_execute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alter_execute',
            name='UID',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True),
        ),
    ]
