# Generated by Django 2.2.1 on 2019-09-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alter_execute', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alter_execute',
            name='databaseid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='alter_execute',
            name='hospitalid',
            field=models.IntegerField(),
        ),
    ]
