# Generated by Django 2.2.1 on 2019-08-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alter_execute', '0002_alter_execute_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='alter_execute',
            name='Exports',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
