# Generated by Django 2.2.1 on 2019-08-30 11:58

from django.db import migrations
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Alter_execute', '0002_auto_20190829_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alter_execute',
            name='UID',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22),
        ),
    ]
