# Generated by Django 2.2.1 on 2019-06-20 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alterauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Permissions',
            field=models.BooleanField(default=False),
        ),
    ]
