# Generated by Django 2.2.1 on 2019-08-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alt_Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Database', models.CharField(max_length=50)),
                ('counts', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'alt_database_dict',
            },
        ),
        migrations.CreateModel(
            name='Alt_Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hospital', models.CharField(max_length=50)),
                ('counts', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'alt_hospital_dict',
            },
        ),
        migrations.CreateModel(
            name='Alt_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AltType', models.CharField(max_length=50)),
                ('counts', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'alt_type_dict',
            },
        ),
    ]
