# Generated by Django 2.2.1 on 2019-07-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AltType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AltType', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'alt_type_dict',
            },
        ),
        migrations.CreateModel(
            name='DBname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Database', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'alt_db_dict',
            },
        ),
    ]
