# Generated by Django 2.2.1 on 2019-09-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alt_Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbname', models.CharField(max_length=50)),
                ('modifier', models.CharField(max_length=50)),
                ('modifytime', models.DateTimeField(auto_now=True)),
                ('begintime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'alt_database_dict',
            },
        ),
        migrations.CreateModel(
            name='Alt_Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalname', models.CharField(max_length=50)),
                ('modifier', models.CharField(max_length=50)),
                ('modifytime', models.DateTimeField(auto_now=True)),
                ('begintime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'alt_hospital_dict',
            },
        ),
        migrations.CreateModel(
            name='Alt_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altertypename', models.CharField(max_length=50)),
                ('modifier', models.CharField(max_length=50)),
                ('modifytime', models.DateTimeField(auto_now=True)),
                ('begintime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'alt_type_dict',
            },
        ),
    ]
