# Generated by Django 2.2.1 on 2019-07-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alter_Dict', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbname',
            old_name='Datebase',
            new_name='Database',
        ),
    ]
