# Generated by Django 2.2.1 on 2019-07-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alter_Dict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbname',
            name='counts',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
