# Generated by Django 2.2.1 on 2019-07-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alter_Dict', '0002_dbname_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='alttype',
            name='counts',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
