# Generated by Django 2.2.1 on 2019-09-02 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alter_Dict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alter_managment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('associatednumber', models.CharField(max_length=50)),
                ('altercontent', models.TextField(max_length=1000)),
                ('informant', models.CharField(max_length=50)),
                ('filltime', models.DateTimeField(auto_now=True)),
                ('reviewer', models.CharField(max_length=50, null=True)),
                ('reviewstatus', models.CharField(default='0', max_length=2, null=True)),
                ('reviewcontent', models.TextField(max_length=1000, null=True)),
                ('audittime', models.DateTimeField(null=True)),
                ('altertypenumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AltType_datas', to='Alter_Dict.Alt_Type')),
                ('dbnumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DBtype_datas', to='Alter_Dict.Alt_Database')),
            ],
            options={
                'db_table': 'alt_managment',
            },
        ),
        migrations.CreateModel(
            name='Alter_managment_checked',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('associatednumber', models.CharField(max_length=50)),
                ('altercontent', models.TextField(max_length=1000)),
                ('informant', models.CharField(max_length=50)),
                ('filltime', models.DateTimeField(auto_now=True)),
                ('reviewer', models.CharField(max_length=50, null=True)),
                ('reviewstatus', models.CharField(default='0', max_length=2, null=True)),
                ('reviewcontent', models.TextField(max_length=1000, null=True)),
                ('audittime', models.DateTimeField(null=True)),
                ('state', models.CharField(default='1', max_length=2)),
                ('alterid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Alter_management.Alter_managment')),
                ('alttypenumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_AltType_datas', to='Alter_Dict.Alt_Type')),
                ('dbnumber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_Database_datas', to='Alter_Dict.Alt_Database')),
            ],
            options={
                'db_table': 'alter_managment_checked',
            },
        ),
    ]
