# Generated by Django 2.2.1 on 2019-07-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alter_managment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('AlterType', models.CharField(max_length=100)),
                ('AssociatedNumber', models.CharField(max_length=50)),
                ('Datebase', models.CharField(max_length=50)),
                ('AlterContent', models.TextField(max_length=1000)),
                ('Informant', models.CharField(max_length=50)),
                ('FillTime', models.DateTimeField(auto_now=True)),
                ('Reviewer', models.CharField(max_length=50, null=True)),
                ('ReviewStatus', models.CharField(default='0', max_length=2, null=True)),
                ('ReviewContent', models.TextField(max_length=1000, null=True)),
                ('AuditTime', models.DateTimeField(null=True)),
                ('Expstatus', models.BooleanField()),
            ],
            options={
                'db_table': 'alt_managment',
            },
        ),
    ]
