# Generated by Django 2.2.1 on 2019-05-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alter_managment',
            fields=[
                ('AlterID', models.AutoField(primary_key=True, serialize=False)),
                ('AlterType', models.CharField(max_length=100)),
                ('AssociatedNumber', models.CharField(max_length=50)),
                ('Datebase', models.CharField(max_length=50)),
                ('AlterContent', models.CharField(max_length=255)),
                ('Informant', models.CharField(max_length=50)),
                ('FillTime', models.DateTimeField(auto_now=True)),
                ('Reviewer', models.CharField(max_length=50, null=True)),
                ('ReviewStatus', models.CharField(max_length=2, null=True)),
                ('ReviewContent', models.CharField(max_length=255, null=True)),
                ('AuditTime', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'Alter_managment',
            },
        ),
    ]
