# Generated by Django 2.2.1 on 2019-08-28 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alter_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alter_managment_checked',
            old_name='AltTypeNumber',
            new_name='AltType',
        ),
        migrations.RenameField(
            model_name='alter_managment_checked',
            old_name='DatabaseNumber',
            new_name='Database',
        ),
    ]
