# Generated by Django 2.2.1 on 2019-07-02 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alter_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alter_managment',
            name='Datebase',
            field=models.ForeignKey(db_column='Database', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Alter_Dict.DBname'),
        ),
    ]
