# Generated by Django 2.2.1 on 2019-09-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alter_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alter_managment',
            name='altercontent',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='alter_managment_checked',
            name='altercontent',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='alter_managment_checked',
            name='reviewcontent',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
