# Generated by Django 2.2.1 on 2019-05-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alter_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alter_managment',
            name='AlterContent',
            field=models.TextField(max_length=1000),
        ),
    ]
