# Generated by Django 2.2.1 on 2019-09-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alter_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alter_managment',
            options={'permissions': (('review_alter_managment', '審核數據權限'),)},
        ),
        migrations.AlterField(
            model_name='alter_managment',
            name='altertypeid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='alter_managment',
            name='databaseid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='alter_managment_checked',
            name='alterid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='alter_managment_checked',
            name='altertypeid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='alter_managment_checked',
            name='databaseid',
            field=models.IntegerField(),
        ),
    ]
