# Generated by Django 2.2.1 on 2019-09-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alter_management', '0002_auto_20190902_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alter_managment',
            name='reviewcontent',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
