# Generated by Django 2.2.1 on 2019-07-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alter_management', '0002_auto_20190702_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alter_managment',
            name='Expstatus',
            field=models.BooleanField(default=False),
        ),
    ]
