# Generated by Django 2.2.1 on 2019-05-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alter_management', '0002_auto_20190528_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alter_managment',
            name='ReviewContent',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='alter_managment',
            name='ReviewStatus',
            field=models.CharField(default=1, max_length=2, null=True),
        ),
    ]
