# Generated by Django 2.2.1 on 2019-08-30 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alter_management', '0002_auto_20190828_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='alter_managment_checked',
            name='AlterID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Alter_management.Alter_managment'),
        ),
    ]
