# Generated by Django 2.2.1 on 2019-09-05 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alter_management', '0003_auto_20190905_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alter_managment_checked',
            name='altercontent',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='alter_managment_checked',
            name='alttypenumber',
            field=models.ForeignKey(db_column='alttypenumber', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_AltType_datas', to='Alter_Dict.Alt_Type'),
        ),
        migrations.AlterField(
            model_name='alter_managment_checked',
            name='dbnumber',
            field=models.ForeignKey(db_column='dbnumber', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_Database_datas', to='Alter_Dict.Alt_Database'),
        ),
    ]
