# Generated by Django 2.2.1 on 2019-07-04 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alter_Dict', '0001_initial'),
        ('Alter_management', '0003_auto_20190702_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alter_managment',
            old_name='Datebase',
            new_name='Database',
        ),
        migrations.RemoveField(
            model_name='alter_managment',
            name='AlterType',
        ),
        migrations.AddField(
            model_name='alter_managment',
            name='AltType',
            field=models.ForeignKey(db_column='AltType', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Alter_Dict.AltType'),
        ),
    ]
